builds:
- id: http-echo
  dir: .
  main: .
  flags:
    - -tags
    - netgo
  ldflags:
    - -s -w
    - -extldflags "-static"
  # defaultBaseImage: scratch
  platforms:
    - linux/amd64
    - linux/arm64
