defaultPlatforms:
  - linux/amd64
  - linux/arm64

builds:
  - id: http-echo
    flags:
      - -tags
      - netgo
    ldflags:
      - -s -w
      - -extldflags "-static"
    env:
      - CGO_ENABLED=0
