
name: Publish

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20
    - env:
        KO_DOCKER_REPO: index.docker.io/${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        go install github.com/google/ko@latest
        echo "${DOCKERHUB_TOKEN}" | ko login index.docker.io --username "${DOCKERHUB_USERNAME}" --password-stdin
        ko build ./
