
name: Publish

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20
    - name: Set up ko
      uses: ko-build/setup-ko@v0.6
    - run: ko build
